#pragma once

#include "defines.h"

/* File for handling shaders
 * Shader objects should handle the following:
 * Its source, aka a filepath to the file
 * If it is being used
 * A pointer to its location in memory
 * 
 */

#define FRAGMENT_SHADER 1
#define VERTEX_SHADER 0

//TODO: Add hot-reloading shaders
typedef struct ShaderObject {
    u32 id;
    //TODO: Find a way of inferring type
    u8 type;
    string filepath;
    string content;
    /* Shader generated by OpenGL */
    u32 GLShader;
} ShaderObject;

b8 RegisterNewShaderObject(ShaderObject* object, u32* shaderProgram);

// NOTE: Passing char* instead of string to avoid messing up void pointer stuff
char* GLGetShaderContent(ShaderObject* object);

b8 GLCompileShader(ShaderObject* object);

b8 GLShaderInitializeShaderProgram(u32* shaderProgram);

b8 GLLinkShaderProgram(u32* shaderProgram);